aws.region=${AWS_REGION:us-east-2}

aws.accessKeyId=${AWS_ACCESS_KEY_ID:}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY:}

#Modelos ANTHROPIC
app.bedrock.anthropic-id=us.anthropic.claude-opus-4-6-v1

#Modelos OPENAPI
app.bedrock.gpt-id=openai.gpt-oss-120b-1:0

#Modelos AMAZON
app.bedrock.amazon-id=us.amazon.nova-2-lite-v1:0

#Modelos MAGISTRAL
app.bedrock.magistral.small-id=mistral.magistral-small-2509

# OpenAPI / Swagger
quarkus.smallrye-openapi.info-title=Nitra AI API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API para envio de prompts aos modelos configurados no Amazon Bedrock.
quarkus.swagger-ui.always-include=true
quarkus.bedrock.devservices.enabled=false

# Cognito / OIDC
quarkus.oidc.auth-server-url=${COGNITO_ISSUER_URL:}
quarkus.oidc.application-type=service
quarkus.oidc.client-id=${COGNITO_CLIENT_ID:}
quarkus.oidc.roles.role-claim-path=scope
quarkus.oidc.roles.role-claim-separator=

%test.quarkus.oidc.enabled=false
